set(viewer_HEADERS include/Viewer.hpp include/ViewController.hpp)

install(
    TARGETS ${TARGETS}
    LIBRARY DESTINATION "${PROJECT_LIBRARY_INSTALL_DIR}"
    ARCHIVE DESTINATION "${PROJECT_LIBRARY_INSTALL_DIR}"
)
install(FILES ${viewer_HEADERS} DESTINATION "${PROJECT_INCLUDE_INSTALL_DIR}")
install(
    FILES "${CMAKE_CURRENT_BINARY_DIR}/${PROJECT_NAME}Config.cmake"
    DESTINATION "${PROJECT_CONFIG_INSTALL_DIR}"
)
