set(PROJ_HEADERS ${PROJ_INCDIR}/Viewer.hpp ${PROJ_INCDIR}/ViewController.hpp)

install(
    # TARGETS ${PROJ_TARGETS}
    TARGETS ${PROJECT_NAME}
    LIBRARY DESTINATION "${PKG_LIBDIR}"
    ARCHIVE DESTINATION "${PKG_LIBDIR}"
)
install(FILES ${PROJ_HEADERS} DESTINATION "${PKG_INCDIR}")
install(FILES "${PKG_CONFFILE}" DESTINATION "${PKG_CONFDIR}")
