configure_package_config_file(
    "${CMAKE_CURRENT_LIST_DIR}/${PROJECT_NAME}Config.cmake.in"
    "${CMAKE_CURRENT_BINARY_DIR}/${PROJECT_NAME}Config.cmake"
    INSTALL_DESTINATION "${PROJECT_CONFIG_INSTALL_DIR}"
    PATH_VARS PROJECT_INCLUDE_INSTALL_DIR PROJECT_LIBRARY_INSTALL_DIR
)
