include(GNUInstallDirs)
include(CMakePackageConfigHelpers)

set(PKG_LIBDIR "${CMAKE_INSTALL_LIBDIR}")
set(PKG_INCDIR "${CMAKE_INSTALL_INCLUDEDIR}/${PROJECT_NAME}")
set(PKG_CONFDIR "${CMAKE_INSTALL_LIBDIR}/cmake/${PROJECT_NAME}")
set(PKG_CONFFILE "${CMAKE_CURRENT_BINARY_DIR}/${PROJECT_NAME}Config.cmake")
set(PKG_CONFFILE_IN "${CMAKE_CURRENT_LIST_DIR}/${PROJECT_NAME}Config.cmake.in")

configure_package_config_file(
    ${PKG_CONFFILE_IN}
    ${PKG_CONFFILE}
    INSTALL_DESTINATION "${PKG_CONFDIR}"
    INSTALL_PREFIX "${CMAKE_INSTALL_PREFIX}"
    PATH_VARS PKG_INCDIR PKG_LIBDIR
)
