file(
    GLOB_RECURSE viewer_SRC
    CONFIGURE_DEPENDS
    "${CMAKE_CURRENT_SOURCE_DIR}/src/*.cpp"
)

set(PROJECT_INCLUDE_INSTALL_DIR "${CMAKE_INSTALL_INCLUDEDIR}/${PROJECT_NAME}")
set(PROJECT_LIBRARY_INSTALL_DIR "${CMAKE_INSTALL_LIBDIR}")
set(PROJECT_CONFIG_INSTALL_DIR "${CMAKE_INSTALL_LIBDIR}/cmake/${PROJECT_NAME}")

set(PUBLIC_LIBS ${OCCT_LIBS} PkgConfig::GTK4)
set(PRIVATE_LIBS PkgConfig::EGL peel::Gtk)

set(INCLUDE_DIRS ${CMAKE_CURRENT_SOURCE_DIR}/include ${OpenCASCADE_INCLUDE_DIR})
