set(PROJ_HEADERS ${PROJ_INCDIR}/Viewer.hpp ${PROJ_INCDIR}/ViewController.hpp)

install(
  TARGETS ${PROJECT_NAME}
  RUNTIME DESTINATION "${CMAKE_INSTALL_BINDIR}"
  LIBRARY DESTINATION "${PKG_LIBDIR}"
  ARCHIVE DESTINATION "${PKG_LIBDIR}")
install(FILES ${PROJ_HEADERS} DESTINATION "${PKG_INCDIR}")
install(FILES "${PKG_CONFFILE}" DESTINATION "${PKG_CONFDIR}")
