find_package(PkgConfig REQUIRED)
pkg_check_modules(GTK4 REQUIRED IMPORTED_TARGET gtk4)

if(IS_NIX)
  set(OpenGL_GL_PREFERENCE "GLVND")
  pkg_check_modules(EGL REQUIRED IMPORTED_TARGET egl)
  find_package(OpenGL REQUIRED)
elseif(IS_WIN AND USE_GLES)
  pkg_check_modules(EGL REQUIRED IMPORTED_TARGET angleproject)
  pkg_get_variable(EGL_INCDIR angleproject includedir)
elseif(USE_GLES)
  pkg_check_modules(EGL REQUIRED IMPORTED_TARGET egl)
else()
  find_package(OpenGL REQUIRED)
endif()

find_package(peel REQUIRED)
peel_generate(Gtk 4.0 RECURSIVE)

find_package(OpenCASCADE REQUIRED)
if(NOT OpenCASCADE_FOUND)
  message(
    FATAL_ERROR
      "could not find OpenCASCADE, please set OpenCASCADE_DIR variable")
else()
  message(STATUS "Using OpenCASCADE from \"${OpenCASCADE_INSTALL_PREFIX}\"")
  message(STATUS "OpenCASCADE_INCLUDE_DIR=${OpenCASCADE_INCLUDE_DIR}")
  message(STATUS "OpenCASCADE_LIBRARY_DIR=${OpenCASCADE_LIBRARY_DIR}")
  message(STATUS "OCCT Libraries: ${OpenCASCADE_Visualization_LIBRARIES}")
endif()

set(PROJ_PRIVATE_LIBS PkgConfig::GTK4 peel::Gtk)
if(IS_NIX)
  list(APPEND PROJ_PRIVATE_LIBS ${OPENGL_LIBRARIES} PkgConfig::EGL)
elseif(USE_GLES)
  list(APPEND PROJ_PRIVATE_LIBS PkgConfig::EGL)
else()
  list(APPEND PROJ_PRIVATE_LIBS ${OPENGL_LIBRARIES})
endif()
